### ISSUE TITLE
显示安装成功了，但是打不开api和后台

### ISSUE THREAD

**Issue by dockerliu** [ijry/uniadmin#2]
显示安装成功，
![image](https://user-images.githubusercontent.com/57223447/90012297-07601380-dc9b-11ea-9885-198c9d426a10.png)

但是打不开后台，
![image](https://user-images.githubusercontent.com/57223447/90015596-b81ce180-dca0-11ea-9e60-226293db6c68.png)

**Comment by ijry** [comment]
看着应该是URL伪静态问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dockerliu <notifications@github.com&gt;
发送时间: 2020年8月12日 22:38
收件人: ijry/uniadmin <uniadmin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[ijry/uniadmin] 显示安装成功了，但是打不开api和后台 (#2)





 
显示安装成功，
 
 
但是打不开后台，

**Comment by dockerliu** [comment]
y
